
# This will run on Travis' 'new' container-based infrastructure
sudo: false

# Blacklist
branches:
  only:
    - master

# Environment variables
env:
  global:
    - GH_REPO_NAME: assetQC
    - DOXYFILE: $TRAVIS_BUILD_DIR/Doxyfile
    - GH_REPO_REF: github.com/david-cattermole/assetQC.git

# Install dependencies
addons:
  apt:
    packages:
      - doxygen
      - doxygen-doc
      - doxygen-latex
      - doxygen-gui
      - graphviz

# Python versions
language: python
python:
  - "2.7"

# Command to install dependencies
install:
  - "pip install coverage"
#  - "pip install -r requirements.txt"

# Build your code e.g. by calling make
script:
  - ./runTests.sh

# Generate and deploy documentation
after_success:
  - cd $TRAVIS_BUILD_DIR
  - chmod +x generateDocs.sh
  - ./generateDocs.sh
